export default function Head() {
  // GLOBAL HEAD
  let worshipname = process.env.WORSHIP_NAME;
  let name = process.env.npm_package_name;
  let title=`${worshipname} - ${name}`.toUpperCase();
  return (
    <>
      <title>{title}</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
